Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20201102.0.0"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.memory = "4096"
     vb.cpus = 4
     # Clipboard'ing
     vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
     # Set the video memory to 128Mb:
     vb.customize ["modifyvm", :id, "--vram", "64"]
     vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
     vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
  end

  $script = <<-SHELL
    sudo apt update -y
    sudo apt install -y gnome-session gdm3 gnome-terminal tmux nmon net-tools menulibre
    sudo reboot
  SHELL
  config.vm.provision "shell", inline: $script, privileged: false
end
